CREATE TABLE Fabricantes (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE Produtos (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NULL,
  id_fabricante INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (id_fabricante) REFERENCES Fabricantes(id)
);